#!/bin/sh

sxhkd &
feh --bg-center /home/oxagast/Photos/bsd-wallpaper_2654222.jpg &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config pointer_modifier mod1
#bspc config pointer_action1 move
#bspc config pointer_action2 reesize_corner
